// swift-tools-version: 6.2
import PackageDescription

// This package deliberately exposes deterministic production logic for focused CI tests.
// GitHub's xcode-27 hosted runner provides macOS 27; the app remains an independent Xcode target.
let portableProductionSources = [
    "MCP/Installer/CodexMCPInstaller.swift",
    "Models/EvaluationFieldAssertion.swift",
    "Models/EvaluationScoringTypes.swift",
    "Models/ScenarioModels.swift",
    "Models/WorkflowTimelineInterval.swift",
    "Services/EvaluationFieldAssertions.swift",
    "Services/MetricScorer.swift",
    "Services/ScenarioComparison.swift",
    "Services/ScenarioExecutionRecovery.swift",
    "Services/ScenarioPersistence.swift",
    "Services/ScenarioValidation.swift",
    "Services/XCTestEvidenceImporter.swift",
    "Services/XCTestRunInvocationTransport.swift",
    "Services/XcodeConnectionDiscovery.swift",
    "Services/XcodeTestExecutor.swift",
]

let portableTestSources = [
    "CodexMCPInstallerTests.swift",
    "EvaluationFieldAssertionTests.swift",
    "MetricScorerTests.swift",
    "WorkflowTimelineIntervalTests.swift",
    "NavigationInteractionTests.swift",
    "TimelineRenderingTests.swift",
    "RunToolbarProgressTests.swift",
    "ScenarioContractsTests.swift",
]

let package = Package(
    name: "FoundationEvalsPortable",
    platforms: [.macOS(.v26), .iOS(.v26)],
    products: [
        .library(name: "FoundationEvalsDeveloper", targets: ["FoundationEvalsDeveloper"]),
    ],
    targets: [
        .target(
            name: "FoundationEvalsDeveloper",
            path: "Sources/FoundationEvalsDeveloper"
        ),
        .target(
            name: "FoundationEvals",
            path: "FoundationEvals/FoundationEvals",
            exclude: [
                "AppIcon.icon",
                "Assets.xcassets",
                "ContentView.swift",
                "FoundationEvalsApp.swift",
                "MCP/Installer/MCPSettingsController.swift",
                "MCP/MCPJSON.swift",
                "MCP/MCPProtocolHandler.swift",
                "MCP/MCPServer.swift",
                "MCP/MCPToolCatalog.swift",
                "Models/EvaluationBuiltinToolTrace.swift",
                "Models/EvaluationConversation.swift",
                "Models/EvaluationCoreAIConfiguration.swift",
                "Models/EvaluationFeatureConfiguration.swift",
                "Models/EvaluationJudgeTrace.swift",
                "Models/EvaluationLiveResponse.swift",
                "Models/EvaluationModelCustomization.swift",
                "Models/EvaluationModels.swift",
                "Models/EvaluationRefusalTrace.swift",
                "Models/EvaluationRunAnalysis.swift",
                "Models/EvaluationSpotlightConfiguration.swift",
                "Models/EvaluationTranscriptTrace.swift",
                "Models/EvaluationVisionToolConfiguration.swift",
                "Models/EvaluationWorkflowTrace.swift",
                "Models/WorkflowTracePresentation.swift",
                "Resources",
                "Services/TelemetryController.swift",
                "Services/CoreAIModelLoader.swift",
                "Services/EvaluationConversationRuntime.swift",
                "Services/EvaluationCustomTool.swift",
                "Services/EvaluationDynamicProfile.swift",
                "Services/EvaluationExactCriterion.swift",
                "Services/EvaluationFeatureResponse.swift",
                "Services/EvaluationHTTPLanguageModel.swift",
                "Services/EvaluationJudge.swift",
                "Services/EvaluationRunner+Judge.swift",
                "Services/EvaluationRunner+Prompt.swift",
                "Services/EvaluationRunner+Support.swift",
                "Services/EvaluationRunner.swift",
                "Services/EvaluationWorkflowRecorder.swift",
                "Services/EvaluationWorkflowHTTPRequest.swift",
                "Services/EvaluationSchemaBuilder.swift",
                "Services/EvaluationSpotlightSearchRuntime.swift",
                "Services/FoundationEvalsMCPRuntime.swift",
                "Services/MCPStoreAuthority.swift",
                "Services/ModelExecutionConfiguration.swift",
                "Services/ReferenceLookupTool.swift",
                "Stores",
                "Support",
                "Views",
            ],
            sources: portableProductionSources
        ),
        .target(
            name: "FoundationEvalsUIComponents",
            path: "FoundationEvals/FoundationEvals/Views/Components",
            sources: ["SidebarNavigationList.swift", "FullWidthDisclosureStyle.swift", "SolidTimelineBar.swift", "RunToolbarProgress.swift"]
        ),
        .testTarget(
            name: "FoundationEvalsPortableTests",
            dependencies: ["FoundationEvals", "FoundationEvalsUIComponents"],
            path: "FoundationEvals/FoundationEvalsTests",
            exclude: [
                "AccessibilitySelectionActionsTests.swift",
                "AttachmentImportTests.swift",
                "CoreAIModelLoaderTests.swift",
                "CustomToolTests.swift",
                "EvaluationConversationTests.swift",
                "EvaluationDynamicProfileTests.swift",
                "EvaluationExactCriterionTests.swift",
                "EvaluationHTTPLanguageModelTests.swift",
                "EvaluationJudgeTests.swift",
                "EvaluationRunAnalysisTests.swift",
                "EvaluationStoreRunLifecycleTests.swift",
                "FeaturePersistenceTests.swift",
                "FoundationEvalsTests.swift",
                "ImageToolTests.swift",
                "MCPFeatureTests.swift",
                "MCPProtocolTests.swift",
                "MCPProviderConfigurationTests.swift",
                "MCPStoreAuthorityTests.swift",
                "MCPTransportRegressionTests.swift",
                "ModelCustomizationTests.swift",
                "ReferenceLookupToolBoundaryTests.swift",
                "RefusalExplanationTests.swift",
                "RunBaselineSelectionTests.swift",
                "SchemaCustomizationTests.swift",
                "SpotlightSearchToolTests.swift",
                "TelemetryControllerTests.swift",
                "TraceTests.swift",
                "EvaluationWorkflowCaptureTests.swift",
                "WorkflowTracePresentationTests.swift",
                "TranscriptTraceTests.swift",
            ],
            sources: portableTestSources
        ),
        .testTarget(
            name: "FoundationEvalsDeveloperTests",
            dependencies: ["FoundationEvalsDeveloper"],
            path: "Tests/FoundationEvalsDeveloperTests"
        ),
    ]
)
