// swift-tools-version: 6.2
import PackageDescription

// This package deliberately exposes deterministic production logic for focused CI tests.
// GitHub's xcode-27 hosted runner provides macOS 27; the app remains an independent Xcode target.
let portableProductionSources = [
    "MCP/Installer/CodexMCPInstaller.swift",
    "Models/EvaluationFieldAssertion.swift",
    "Models/EvaluationScoringTypes.swift",
    "Models/ScenarioModels.swift",
    "Models/ScenarioExecutionModels.swift",
    "Models/ScenarioCollectionModels.swift",
    "Models/WorkflowTimelineInterval.swift",
    "Services/EvaluationFieldAssertions.swift",
    "Services/MetricScorer.swift",
    "Services/ScenarioComparison.swift",
    "Services/ScenarioExecutionComparison.swift",
    "Services/ScenarioExecutionRecovery.swift",
    "Services/ScenarioExpectationAuthoring.swift",
    "Services/ScenarioCollectionService.swift",
    "Services/ScenarioCollectionStore.swift",
    "Services/IntentEvidenceBundle.swift",
    "Services/IntentEvidenceQualification.swift",
    "Services/ScenarioPersistence.swift",
    "Services/ScenarioValidation.swift",
    "Services/XCTestEvidenceImporter.swift",
    "Services/XCTestRunInvocationTransport.swift",
    "Services/XcodeConnectionDiscovery.swift",
    "Services/XcodeTestExecutor.swift",
    "Services/OpenStepProjectDocument.swift",
    "Services/IntentLabProjectInstaller.swift",
]

let portableTestSources = [
    "CodexMCPInstallerTests.swift",
    "EvaluationFieldAssertionTests.swift",
    "MetricScorerTests.swift",
    "WorkflowTimelineIntervalTests.swift",
    "NavigationInteractionTests.swift",
    "TimelineRenderingTests.swift",
    "RunToolbarProgressTests.swift",
    "ScenarioContractsTests.swift",
    "ScenarioExpectationAuthoringTests.swift",
    "ScenarioExecutionPlanTests.swift",
    "ScenarioCollectionTests.swift",
    "ScenarioNoMutationTests.swift",
    "ScenarioExecutionComparisonTests.swift",
    "ScenarioV3HarnessBridgeTests.swift",
    "ScenarioActionParityTests.swift",
    "IntentEvidenceBundleTests.swift",
    "IntentLabProjectInstallerTests.swift",
    "ExecutorSimplificationTests.swift",
    "XcodeBundleLayoutTests.swift",
]

let package = Package(
    name: "FoundationEvalsPortable",
    platforms: [.macOS(.v26), .iOS(.v26)],
    products: [
        .library(name: "FoundationEvalsDeveloper", targets: ["FoundationEvalsDeveloper"]),
        .library(name: "IntentLabContracts", targets: ["IntentLabContracts"]),
        .library(name: "IntentLabTesting", targets: ["IntentLabTesting"]),
        .library(name: "IntentLabCoreTesting", targets: ["IntentLabCoreTesting"]),
        .executable(name: "intents-evidence", targets: ["IntentsEvidenceCLI"]),
        .executable(name: "intents-evals", targets: ["ProductionEvalsCLI"]),
    ],
    dependencies: [.package(path: "Packages/ProductionEvals")],
    targets: [
        .executableTarget(name: "ProductionEvalsCLI", dependencies: [.product(name: "ProductionEvals", package: "ProductionEvals")], path: "Sources/ProductionEvalsCLI"),
        .target(name: "IntentLabContracts", path: "Sources/IntentLabContracts"),
        .target(
            name: "IntentLabSiriBridge",
            path: "Sources/IntentLabSiriBridge",
            publicHeadersPath: "include"
        ),
        .target(
            name: "IntentLabCoreTesting",
            dependencies: ["IntentLabContracts", "IntentLabSiriBridge"],
            path: "Sources/IntentLabCoreTesting"
        ),
        .target(
            name: "IntentLabTesting",
            dependencies: ["IntentLabContracts", "IntentLabCoreTesting"],
            path: "Sources/IntentLabTesting"
        ),
        .target(
            name: "FoundationEvalsDeveloper",
            dependencies: [.product(name: "ProductionEvals", package: "ProductionEvals")],
            path: "Sources/FoundationEvalsDeveloper"
        ),
        .executableTarget(
            name: "IntentsEvidenceCLI",
            dependencies: ["FoundationEvals"],
            path: "Sources/IntentsEvidenceCLI"
        ),
        .target(
            name: "FoundationEvals",
            path: "FoundationEvals/FoundationEvals",
            exclude: [
                "AppIcon.icon",
                "Assets.xcassets",
                "ContentView.swift",
                "FoundationEvalsApp.swift",
                "MCP/Installer/MCPSettingsController.swift",
                "MCP/MCPJSON.swift",
                "MCP/MCPProtocolHandler.swift",
                "MCP/MCPServer.swift",
                "MCP/MCPToolCatalog.swift",
                "Models/EvaluationBuiltinToolTrace.swift",
                "Models/EvaluationConversation.swift",
                "Models/EvaluationCoreAIConfiguration.swift",
                "Models/EvaluationFeatureConfiguration.swift",
                "Models/EvaluationJudgeTrace.swift",
                "Models/EvaluationLiveResponse.swift",
                "Models/EvaluationModelCustomization.swift",
                "Models/EvaluationModels.swift",
                "Models/EvaluationReviewModels.swift",
                "Models/EvaluationJudgeCalibration.swift",
                "Services/EvaluationReviewWorkflow.swift",
                "MCP/EvaluationReviewMCP.swift",
                "Models/EvaluationRefusalTrace.swift",
                "Models/EvaluationRunAnalysis.swift",
                "Models/EvaluationSpotlightConfiguration.swift",
                "Models/EvaluationTranscriptTrace.swift",
                "Models/EvaluationVisionToolConfiguration.swift",
                "Models/EvaluationWorkflowTrace.swift",
                "Models/WorkflowTracePresentation.swift",
                "Resources",
                "Services/TelemetryController.swift",
                "Services/NativeProductionExecutor.swift",
                "MCP/MCPControlContracts.swift",
                "MCP/MCPActionDiscovery.swift",
                "MCP/MCPWorkspaceTools.swift",
                "MCP/MCPProductionTools.swift",
                "MCP/MCPDeviceTools.swift",
                "Services/EvaluationAppControl.swift",
                "Services/MCPControlService.swift",
                "Services/MCPWorkspaceControl.swift",
                "Services/MCPProductionControl.swift",
                "Services/MCPDeviceControl.swift",
                "Services/MCPIntentInstallation.swift",

                "Services/ProductionNativeWorkerCommand.swift",
                "Services/CoreAIModelLoader.swift",
                "Services/EvaluationConversationRuntime.swift",
                "Services/EvaluationCustomTool.swift",
                "Services/EvaluationDynamicProfile.swift",
                "Services/EvaluationExactCriterion.swift",
                "Services/EvaluationFeatureResponse.swift",
                "Services/EvaluationHTTPLanguageModel.swift",
                "Services/EvaluationJudge.swift",
                "Services/EvaluationRunner+Judge.swift",
                "Services/EvaluationRunner+Prompt.swift",
                "Services/EvaluationRunner+Support.swift",
                "Services/EvaluationRunner.swift",
                "Services/EvaluationWorkflowRecorder.swift",
                "Services/EvaluationWorkflowHTTPRequest.swift",
                "Services/EvaluationSchemaBuilder.swift",
                "Services/EvaluationSpotlightSearchRuntime.swift",
                "Services/FoundationEvalsMCPRuntime.swift",
                "Services/MCPStoreAuthority.swift",
                "Services/ModelExecutionConfiguration.swift",
                "Services/ReferenceLookupTool.swift",
                "Stores",
                "Support",
                "Views",
            ],
            sources: portableProductionSources
        ),
        .target(
            name: "FoundationEvalsUIComponents",
            path: "FoundationEvals/FoundationEvals/Views/Components",
            sources: ["SidebarNavigationList.swift", "FullWidthDisclosureStyle.swift", "SolidTimelineBar.swift", "RunToolbarProgress.swift"]
        ),
        .testTarget(
            name: "FoundationEvalsPortableTests",
            dependencies: ["FoundationEvals", "FoundationEvalsUIComponents", "IntentLabContracts"],
            path: "FoundationEvals/FoundationEvalsTests",
            exclude: [
                "Fixtures",
                "AccessibilitySelectionActionsTests.swift",
                "AttachmentImportTests.swift",
                "CoreAIModelLoaderTests.swift",
                "DeveloperRunnerStoreTests.swift",
                "CustomToolTests.swift",
                "EvaluationConversationTests.swift",
                "EvaluationDynamicProfileTests.swift",
                "EvaluationExactCriterionTests.swift",
                "EvaluationHTTPLanguageModelTests.swift",
                "EvaluationJudgeTests.swift",
                "EvaluationRunAnalysisTests.swift",
                "EvaluationReviewWorkflowTests.swift",
                "EvaluationStoreRunLifecycleTests.swift",
                "EvaluationStorePersistenceRecoveryTests.swift",
                "FeaturePersistenceTests.swift",
                "FoundationEvalsTests.swift",
                "ImageToolTests.swift",
                "MCPAppControlTests.swift",
                "MCPActionDiscoveryTests.swift",
                "MCPFeatureTests.swift",
                "MCPProtocolTests.swift",
                "MCPProviderConfigurationTests.swift",
                "MCPStoreAuthorityTests.swift",
                "MCPTransportRegressionTests.swift",
                "ModelCustomizationTests.swift",
                "ReferenceLookupToolBoundaryTests.swift",
                "RefusalExplanationTests.swift",
                "RunBaselineSelectionTests.swift",
                "SchemaCustomizationTests.swift",
                "ScenarioFeatureEvidenceTests.swift",
                "SpotlightSearchToolTests.swift",
                "TelemetryControllerTests.swift",
                "TraceTests.swift",
                "EvaluationWorkflowCaptureTests.swift",
                "WorkflowTracePresentationTests.swift",
                "TranscriptTraceTests.swift",
            ],
            sources: portableTestSources
        ),
        .testTarget(
            name: "FoundationEvalsDeveloperTests",
            dependencies: ["FoundationEvalsDeveloper"],
            path: "Tests/FoundationEvalsDeveloperTests"
        ),
        .testTarget(
            name: "IntentLabContractsTests",
            dependencies: ["IntentLabContracts"],
            path: "Tests/IntentLabContractsTests"
        ),
        .testTarget(
            name: "IntentLabCoreTestingTests",
            dependencies: ["IntentLabCoreTesting", "IntentLabContracts"],
            path: "Tests/IntentLabCoreTestingTests"
        ),
        .testTarget(
            name: "IntentLabTestingTests",
            dependencies: ["IntentLabTesting", "IntentLabContracts"],
            path: "Tests/IntentLabTestingTests"
        ),
    ]
)
