import { readFileSync, writeFileSync } from 'node:fs';

// Keep the authored sheets separate, but deliver their exact cascade in HTML.
// This single-page site avoids two requests before the browser can first paint.
const root = new URL('../dist/', import.meta.url);
const styles = ['styles.css', 'native.css'].map(file => readFileSync(new URL(file, root), 'utf8')).join('\n');
if (/<\/style/i.test(styles)) throw new Error('Styles must not contain an HTML closing style tag');
const block = `<!-- Generated by scripts/inline-styles.mjs; edit the CSS files. -->\n  <style id="site-styles">\n${styles}</style>`;
const path = new URL('index.html', root);
const html = readFileSync(path, 'utf8');
const marker = /<!-- Generated by scripts\/inline-styles\.mjs; edit the CSS files\. -->\n  <style id="site-styles">[\s\S]*?<\/style>/;
const links = /<link rel="stylesheet" href="\/styles\.css">\s*<link rel="stylesheet" href="\/native\.css">/;
if (!marker.test(html) && !links.test(html)) throw new Error('Expected exactly one stylesheet insertion point');
const updated = html.replace(marker.test(html) ? marker : links, () => block);
if (process.argv.includes('--check')) {
  if (html !== updated) throw new Error('Inline styles are stale; run node scripts/inline-styles.mjs');
} else if (html !== updated) {
  writeFileSync(path, updated);
}
